# Generated by Django 4.0.3 on 2022-04-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_range', models.CharField(max_length=5)),
                ('times', models.TextField()),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('number', models.CharField(blank=True, max_length=11)),
                ('item', models.ManyToManyField(to='project.menu_item')),
                ('rescuisine', models.ManyToManyField(to='project.cuisine')),
            ],
        ),
        migrations.AddField(
            model_name='menu_item',
            name='menrestaurant',
            field=models.ManyToManyField(to='project.restaurant'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cuisines', models.ManyToManyField(to='project.cuisine')),
                ('favorites', models.ManyToManyField(to='project.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='cuisine',
            name='cusrestaurant',
            field=models.ManyToManyField(to='project.restaurant'),
        ),
    ]
