# Generated by Django 4.0.3 on 2022-04-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='cusrestaurant',
            field=models.ManyToManyField(blank=True, to='project.restaurant'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='menrestaurant',
            field=models.ManyToManyField(blank=True, to='project.restaurant'),
        ),
    ]
