# Generated by Django 4.0.3 on 2022-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='cusrestaurant',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='menrestaurant',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
