# Generated by Django 4.0.3 on 2022-04-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_cuisine_cusrestaurant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='times',
            new_name='fri_times',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mon_times',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sat_times',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sun_times',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thur_times',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tue_times',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wed_times',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
