# Generated by Django 4.0.3 on 2022-04-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_times_restaurant_fri_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
