# Generated by Django 4.0.3 on 2022-05-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_menuimages_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.CharField(choices=[('onestar', '1 Star'), ('twostar', '2 Stars'), ('threestar', '3 Stars'), ('fourstar', '4 Stars'), ('fivestar', '5 Stars')], default='onestar', max_length=20),
        ),
    ]
