# Generated by Django 4.0.3 on 2022-05-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_reviews_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.CharField(choices=[('onestar', '1 Star'), ('twostar', '2 Stars'), ('threestar', '3 Stars'), ('fourstar', '4 Stars'), ('five stars', '5 Stars')], default='onestar', max_length=20),
        ),
    ]
