# Generated by Django 4.0.3 on 2022-04-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0003_statusmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
